experiment: 'TestPolicy'  #'SimulateOneRound'
experiment_settings:
  num_samples: 10000
  
policy: 'ProbabilityOfExploding'
policy_settings:
  setting1: 1

bag_settings:
  bought_tokens:
    o1: 0
    k1: 0
    y1: 0
    g4: 0

datahandler: 'RepeatSingleRound'