experiment: 'SweepOrange'  #'SimulateOneRound'
experiment_settings:
  num_samples: 10000
  
policy: 'GoBust'
policy_settings:
  setting1: 1
  setting2: 2

bag_settings:
  bought_tokens:
    o1: 0

datahandler: 'RepeatSingleRound'
