from dataclasses import dataclass

import matplotlib.patches as patches
import numpy as np

from engine.constants import COINS, NUM_TILES, RUBY, VICTORY_POINTS
from render.colors import TILE_BASE_COLOR, VICTORY_POINT_COLOR


@dataclass
class SpiralParams:
    a: float = 0.1
    bx: float = 0.21
    by: float = 0.21
    theta_0: float = 0.0
    spacing: float = 1.0
    delta_theta: float = 0.01


def theta2xy(theta, spiral_params: SpiralParams):
    """
    Map a theta value to x, y coordinates for the given spiral parameters a, bx,
    and by.
    """
    x = (spiral_params.a + theta * spiral_params.bx) * np.cos(theta)
    y = (spiral_params.a + theta * spiral_params.by) * np.sin(theta)
    return [x, y]


def make_board_spiral(spiral_params: SpiralParams) -> tuple[np.ndarray, np.ndarray]:
    """
    Generate the spiral points and tile points for the board.
    The spiral points are generated by incrementing theta by delta_theta until
    the distance between the last tile point and the current spiral point is
    greater than or equal to the spacing.
    """

    theta = spiral_params.theta_0

    tile_points = [theta2xy(theta, spiral_params=spiral_params)]
    spiral_points = [theta2xy(theta, spiral_params=spiral_params)]

    while len(tile_points) < NUM_TILES:
        theta += spiral_params.delta_theta
        spiral_points.append(theta2xy(theta, spiral_params=spiral_params))

        # Check the straight line distance between the last tile point and the current spiral point
        last_tile_point = tile_points[-1]
        current_spiral_point = spiral_points[-1]
        distance = np.linalg.norm(
            np.array(current_spiral_point) - np.array(last_tile_point)
        )

        if distance >= spiral_params.spacing:
            tile_points.append(current_spiral_point)

    return np.array(spiral_points), np.array(tile_points)


def draw_tile(ax, index, xy, scale=1.0):
    radius = 0.2 * scale
    circle = patches.Circle(xy, radius=radius, color=TILE_BASE_COLOR, fill=True)
    ax.add_patch(circle)

    width = 0.15 * scale
    height = 0.13 * scale
    xy_anchor = (
        xy[0] + np.cos(np.deg2rad(225)) * radius,
        xy[1] + np.sin(np.deg2rad(225)) * radius,
    )

    # Add number indicating how many victory points the tile is worth
    xy_text = (
        xy[0] + 0.55 * np.cos(np.deg2rad(225)) * radius,
        xy[1] + 0.45 * np.sin(np.deg2rad(225)) * radius,
    )

    ax.text(
        xy_text[0],
        xy_text[1],
        str(VICTORY_POINTS[index]),
        ha="center",
        va="center",
        fontsize=10,
        color="black",
        rasterized=False,
        rotation=10,
    )

    rectangle = patches.Rectangle(
        xy=xy_anchor,
        angle=10,
        width=width,
        height=height,
        color=VICTORY_POINT_COLOR,
        fill=True,
    )
    ax.add_patch(rectangle)

    if RUBY[index]:
        ruby_radius = 0.05 * scale
        radial_offset_factor = 1.0
        xy_ruby = (
            xy[0] + radial_offset_factor * np.sqrt(3) / 2 * radius,
            xy[1] + radial_offset_factor * 0.5 * radius,
        )
        ruby_hexagon = patches.RegularPolygon(
            xy_ruby, numVertices=6, radius=ruby_radius, color="red", fill=True
        )
        ax.add_patch(ruby_hexagon)

    # Write the coin value of the tile in the top center of the circle
    xy_coin = (xy[0], xy[1] + 0.5 * radius)
    ax.text(
        xy_coin[0],
        xy_coin[1],
        str(COINS[index]),
        ha="center",
        va="center",
        fontsize=10,
        color="black",
        rasterized=False,
        rotation=0,
        fontweight="bold",
    )
